---
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  galaxy:
    name: Publish to Ansible Galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Import role to Galaxy
        env:
          GALAXY_TOKEN: ${{ secrets.GALAXY_API_KEY }}
        if: env.GALAXY_TOKEN != ''
        uses: ansible-actions/ansible-galaxy-action@v1.2.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
